import { MediaManifest } from '../types/assets';

// Auto-generated by scripts/media/generate-media-variants.mjs
// Do not edit manually.
export const generatedMediaManifestByKey: MediaManifest = {
  "hero-poster": {
    "key": "hero-poster",
    "source": "/media/images/cars/supercars-trio-front-lineup-coastal-hero.jpg",
    "slots": {
      "hero": [
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w768.avif",
          "width": 768,
          "height": 576,
          "format": "avif",
          "bytes": 33069
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w768.webp",
          "width": 768,
          "height": 576,
          "format": "webp",
          "bytes": 44398
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w768.jpg",
          "width": 768,
          "height": 576,
          "format": "jpg",
          "bytes": 56605
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1280.avif",
          "width": 1280,
          "height": 960,
          "format": "avif",
          "bytes": 74660
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1280.webp",
          "width": 1280,
          "height": 960,
          "format": "webp",
          "bytes": 107490
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1280.jpg",
          "width": 1280,
          "height": 960,
          "format": "jpg",
          "bytes": 139943
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1600.avif",
          "width": 1600,
          "height": 1200,
          "format": "avif",
          "bytes": 102202
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1600.webp",
          "width": 1600,
          "height": 1200,
          "format": "webp",
          "bytes": 154520
        },
        {
          "src": "/media/generated/hero/cars-supercars-trio-front-lineup-coastal-hero-w1600.jpg",
          "width": 1600,
          "height": 1200,
          "format": "jpg",
          "bytes": 203962
        }
      ],
      "card": [
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w480.avif",
          "width": 480,
          "height": 360,
          "format": "avif",
          "bytes": 12440
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w480.webp",
          "width": 480,
          "height": 360,
          "format": "webp",
          "bytes": 18124
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w480.jpg",
          "width": 480,
          "height": 360,
          "format": "jpg",
          "bytes": 22699
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w768.avif",
          "width": 768,
          "height": 576,
          "format": "avif",
          "bytes": 28583
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w768.webp",
          "width": 768,
          "height": 576,
          "format": "webp",
          "bytes": 42050
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w768.jpg",
          "width": 768,
          "height": 576,
          "format": "jpg",
          "bytes": 52727
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w1024.avif",
          "width": 1024,
          "height": 768,
          "format": "avif",
          "bytes": 46511
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w1024.webp",
          "width": 1024,
          "height": 768,
          "format": "webp",
          "bytes": 69382
        },
        {
          "src": "/media/generated/card/cars-supercars-trio-front-lineup-coastal-hero-w1024.jpg",
          "width": 1024,
          "height": 768,
          "format": "jpg",
          "bytes": 88122
        }
      ],
      "thumb": [
        {
          "src": "/media/generated/thumb/cars-supercars-trio-front-lineup-coastal-hero-w160.webp",
          "width": 160,
          "height": 120,
          "format": "webp",
          "bytes": 2650
        },
        {
          "src": "/media/generated/thumb/cars-supercars-trio-front-lineup-coastal-hero-w160.jpg",
          "width": 160,
          "height": 120,
          "format": "jpg",
          "bytes": 2899
        },
        {
          "src": "/media/generated/thumb/cars-supercars-trio-front-lineup-coastal-hero-w320.webp",
          "width": 320,
          "height": 240,
          "format": "webp",
          "bytes": 7748
        },
        {
          "src": "/media/generated/thumb/cars-supercars-trio-front-lineup-coastal-hero-w320.jpg",
          "width": 320,
          "height": 240,
          "format": "jpg",
          "bytes": 8336
        }
      ]
    }
  },
  "logo-color": {
    "key": "logo-color",
    "source": "/media/images/logo/logo-color.png",
    "slots": {
      "logo": [
        {
          "src": "/media/generated/logo/logo-logo-color-w120.webp",
          "width": 120,
          "height": 120,
          "format": "webp",
          "bytes": 1946
        },
        {
          "src": "/media/generated/logo/logo-logo-color-w120.png",
          "width": 120,
          "height": 120,
          "format": "png",
          "bytes": 2459
        },
        {
          "src": "/media/generated/logo/logo-logo-color-w240.png",
          "width": 240,
          "height": 240,
          "format": "png",
          "bytes": 4611
        },
        {
          "src": "/media/generated/logo/logo-logo-color-w240.webp",
          "width": 240,
          "height": 240,
          "format": "webp",
          "bytes": 5048
        },
        {
          "src": "/media/generated/logo/logo-logo-color-w360.png",
          "width": 360,
          "height": 360,
          "format": "png",
          "bytes": 6983
        },
        {
          "src": "/media/generated/logo/logo-logo-color-w360.webp",
          "width": 360,
          "height": 360,
          "format": "webp",
          "bytes": 8580
        }
      ]
    }
  },
  "logo-white": {
    "key": "logo-white",
    "source": "/media/images/logo/logo-white.png",
    "slots": {
      "logo": [
        {
          "src": "/media/generated/logo/logo-logo-white-w120.webp",
          "width": 120,
          "height": 120,
          "format": "webp",
          "bytes": 1392
        },
        {
          "src": "/media/generated/logo/logo-logo-white-w120.png",
          "width": 120,
          "height": 120,
          "format": "png",
          "bytes": 2197
        },
        {
          "src": "/media/generated/logo/logo-logo-white-w240.webp",
          "width": 240,
          "height": 240,
          "format": "webp",
          "bytes": 3522
        },
        {
          "src": "/media/generated/logo/logo-logo-white-w240.png",
          "width": 240,
          "height": 240,
          "format": "png",
          "bytes": 4540
        },
        {
          "src": "/media/generated/logo/logo-logo-white-w360.webp",
          "width": 360,
          "height": 360,
          "format": "webp",
          "bytes": 5892
        },
        {
          "src": "/media/generated/logo/logo-logo-white-w360.png",
          "width": 360,
          "height": 360,
          "format": "png",
          "bytes": 6813
        }
      ]
    }
  }
};
